In [1]:
import numpy as np
from numpy.linalg import det, inv

In [2]:
c = input()
c_key = input()

ALYHAUKCRT
RI JT


In [3]:
c_key = c_key.replace(" ","")
print(c_key)

RIJT


In [4]:
C_Key = np.array([[ord(c_key[0]),ord(c_key[1])],[ord(c_key[2]),ord(c_key[3])]], dtype=np.int32)
C_Key = C_Key - 65
print(C_Key)

[[17  8]
 [ 9 19]]


In [5]:
P_Key = np.array([[ord('T'),ord('H')],[ord('H'),ord('E')]], dtype=np.int32)
P_Key = P_Key - 65
print(P_Key)

[[19  7]
 [ 7  4]]


In [6]:
C_Key_Inv = det(C_Key)*inv(C_Key)
C_Key_Inv = np.around(C_Key_Inv)
C_Key_Inv = C_Key_Inv.astype(int)
print(C_Key_Inv)

[[19 -8]
 [-9 17]]


In [7]:
determinant = det(C_Key)
determinant = int(round(determinant))
determinant = determinant%26
print(determinant)

17


In [8]:
inverse_determinant=0
for i in range(26):
  if(((i*determinant)%26)==1):
    inverse_determinant=i
    break
print(inverse_determinant)

23


In [9]:
C_Key_Inv = inverse_determinant*C_Key_Inv
C_Key_Inv = (C_Key_Inv%26)
print(C_Key_Inv)

[[21 24]
 [ 1  1]]


In [10]:
K_Inv = (np.dot(C_Key_Inv,P_Key))%26
print(K_Inv)

[[21  9]
 [ 0 11]]


In [11]:
length_cipher = len(c)

if (length_cipher%2)!=0:
  c = c+"Z"
  length_cipher += 1

C = np.zeros([int(length_cipher/2),2], dtype = int)

j=0
for i in range(0,length_cipher,2):
  C[j][0] = ord(c[i])-65
  i+=1
  C[j][1] = ord(c[i])-65
  j+=1

print(C)

[[ 0 11]
 [24  7]
 [ 0 20]
 [10  2]
 [17 19]]


In [12]:
P = (np.dot(C,K_Inv))%26 + 65
P = P.flatten()
print(P)

[65 82 75 72 65 77 67 73 84 89]


In [13]:
p=""
for i in P:
  p = p+chr(i)
print(p)

ARKHAMCITY
