In [ ]:
import numpy as np

In [ ]:
l_key = int(input())
key = input()
encrypted_key = input()
plaintext = input()

7
4 3 1 2 5 6 7
ttnaaptmtsuoaodwcoixknlypetz
encryptthistextandsendittoalice


In [ ]:
key = key.replace(" ","")
print(key)

4312567


In [ ]:
key_arranged = np.zeros(l_key, dtype=int)
rows = len(encrypted_key)//l_key
for i in range(l_key):
  key_arranged[i] = key.find(chr(i+ord('1')))
print(key_arranged[1])

3


In [ ]:
key_matrix_encrypted = np.zeros([rows,l_key], dtype=int)

k = 0

for j in range(l_key):
  for i in range(rows):
    key_matrix_encrypted[i][key_arranged[j]] = ord(encrypted_key[k])
    k+=1

print(key_matrix_encrypted)

decrypted_key = ''
k=0
for j in range(rows):
  for i in range(l_key):
    decrypted_key = decrypted_key + chr(key_matrix_encrypted[j][i]);

print(decrypted_key)

[[ 97 116 116  97  99 107 112]
 [111 115 116 112 111 110 101]
 [100 117 110 116 105 108 116]
 [119 111  97 109 120 121 122]]
attackpostponeduntiltwoamxyz


In [ ]:
a = np.zeros(len(plaintext), dtype=int)
for i in range(len(plaintext)):
  a[i] = (ord(plaintext[i])-ord('a') + ord(decrypted_key[i%(len(decrypted_key))])-ord('a'))%26

vigenere = ''
for i in a:
  vigenere = vigenere+chr(i+ord('a'))

print(vigenere)

egvrazihzbhhrbwuawapgzwtflykivx
